name = "novai-widget-injector"
main = "widget-injector.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "novaisystems.online/*"
zone_name = "novaisystems.online"

[[routes]]
pattern = "workbench.novaisystems.online/*"
zone_name = "novaisystems.online"
