name = "novai-widget-injector"
main = "widget-injector.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "novaisystems.online/*"
zone_name = "novaisystems.online"

[[routes]]
pattern = "workbench.novaisystems.online/*"
zone_name = "novaisystems.online"

# To enable server-side lead storage, run:
#   wrangler kv:namespace create WB_LEADS
# Then uncomment below and paste the id:
# [[kv_namespaces]]
# binding = "WB_LEADS"
# id = "YOUR_KV_ID_HERE"
